---
title: "Neuro_report"
format: html
embed-resources: true
editor: visual
---

## STEPCARE - REPORT2

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(dplyr)
library(here)
library(openxlsx)
library(reshape2)
library(tidyr)
library(readxl)
library(stringr)
library(here)
library(tableone)
library(knitr)
library(kableExtra)
library(purrr)
library(gtsummary)
library(gt)
library(flextable)
library(tidymodels)
library(broom)

## Read the other files. 
prep <- readRDS("/Users/josefdankiewicz/Library/CloudStorage/OneDrive-SharedLibraries-LundUniversity/cardiacarrest - Documents/STEPCARE/data/RDS/prep.rds")
```


```{r echo=FALSE, message=FALSE, warning=FALSE}
##################################
## Neuromonitoring #############
##################################

# #1) Timepoint randomisation to prognostication <68 hours? (Y/N), if <68 h, 
# how many hours after randomisation was prognostication performed?

prep$hours.to.prog <- as.numeric(prep$N_PROG_DateTime - prep$randomisation.datetime, units="hours")

## Very high numbers over 120 ##
late_neuroprog <- prep %>% select(StudyPatientID,hours.to.prog) %>% filter(hours.to.prog>120)
## Low numbers over 120 ##
early_neuroprog <- prep %>% select(StudyPatientID,hours.to.prog) %>% filter(hours.to.prog<68)
## Causes ## 


# 2) Timepoint randomisation to WLST cerebral causes < 68 h? If WLST neuro <68h, were there other causes for WLST such as ethical? 



#   Early-neuro:
#   1) If patient unconscious (FOUR-M <=3 on day 2), was a CT performed ≥20 h after randomisation?
#   2) Hours between randomisation and biomarker collection. N/A?
#   3) Was a continuous EEG and/or routine EEG performed ≤32 hours after randomisation?
#   4) If no EEG (continuous or routine) was performed ≤32 h after randomisation, was any EEG performed after this timepoint? If so, how many hours after randomisation?
#   5) Were biomarkers collected around 12 and 24 h after randomisation? Hours from randomisation to collection of 1st, 2nd, 3rd and 4th samples. 
```

